#!/bin/bash
cd "/c/Users/Alex/Desktop/Projects/IELTS website/.claude/worktrees/musing-mcclintock-862665"
V="/c/Users/Alex/AppData/Local/Temp/claude/C--Users-Alex-Desktop-Projects-IELTS-website--claude-worktrees-musing-mcclintock-862665/7ea06528-23bb-4dbf-be18-8c70267e53bf/scratchpad/verify-free"
start=$(date +%s); npx astro check > "$V/astro-check.log" 2>&1; echo "astro check exit=$? secs=$(($(date +%s)-start))" >> "$V/pipeline.log"
start=$(date +%s); env -u PUBLIC_ACCESS_MODE npx astro build --outDir 'C:\Users\Alex\AppData\Local\Temp\claude\C--Users-Alex-Desktop-Projects-IELTS-website--claude-worktrees-musing-mcclintock-862665\7ea06528-23bb-4dbf-be18-8c70267e53bf\scratchpad\verify-free\dist-open' > "$V/build-open.log" 2>&1; echo "open build exit=$? secs=$(($(date +%s)-start))" >> "$V/pipeline.log"
start=$(date +%s); PUBLIC_ACCESS_MODE=trial PUBLIC_SUPABASE_URL=http://127.0.0.1:8841 PUBLIC_SUPABASE_ANON_KEY=local-anon-key PUBLIC_MR_EZ_URL=http://127.0.0.1:8841/tutor PUBLIC_GRADER_URL=http://127.0.0.1:8841/grade-essay PUBLIC_CONTENT_URL=http://127.0.0.1:8841/content PUBLIC_LIVE_EXAMINER_URL=http://127.0.0.1:8841/live PUBLIC_SPEAKING_GRADER_URL=http://127.0.0.1:8841/grade-speaking PUBLIC_PAYMENTS_URL=http://127.0.0.1:8841/payments PUBLIC_PAYMENTS_SIMULATED=1 npx astro build --outDir 'C:\Users\Alex\AppData\Local\Temp\claude\C--Users-Alex-Desktop-Projects-IELTS-website--claude-worktrees-musing-mcclintock-862665\7ea06528-23bb-4dbf-be18-8c70267e53bf\scratchpad\verify-free\dist-gated' > "$V/build-gated.log" 2>&1; echo "gated build exit=$? secs=$(($(date +%s)-start))" >> "$V/pipeline.log"
node --import ./tests/ts-extension-loader.mjs tools/trial-content-audit.mjs 'C:\Users\Alex\AppData\Local\Temp\claude\C--Users-Alex-Desktop-Projects-IELTS-website--claude-worktrees-musing-mcclintock-862665\7ea06528-23bb-4dbf-be18-8c70267e53bf\scratchpad\verify-free\dist-gated' > "$V/leak-audit-gated.log" 2>&1; echo "leak audit (my gated build) exit=$?" >> "$V/pipeline.log"
node --import ./tests/ts-extension-loader.mjs tools/trial-content-audit.mjs 'C:\Users\Alex\AppData\Local\Temp\claude\C--Users-Alex-Desktop-Projects-IELTS-website--claude-worktrees-musing-mcclintock-862665\7ea06528-23bb-4dbf-be18-8c70267e53bf\scratchpad\verify-free\..\review\dist-trial-free' > "$V/leak-audit-review4441.log" 2>&1; echo "leak audit (review 4441 build) exit=$?" >> "$V/pipeline.log"
echo DONE >> "$V/pipeline.log"
