/* The Task 1 chart, for the examiner model to see.

   A Task 1 question reaches this Worker as `promptHtml` with the chart, table,
   map or diagram as an <img> inside it. Stripped to text, the question says
   "The chart below shows..." and the model cannot check a single figure, the
   overview or which key features were selected, which is most of Task
   Achievement. This module finds those images and returns the ones that are
   safe to attach.

   The browser is not a source of truth (CLAUDE.md, Mr EZ rules), so an image
   is attached only when its bytes are, exactly, one of the site's own Task 1
   charts: the SHA-256 of every file in public/pics/writing/imported is built
   into the Worker (./task1-charts.ts, generated by
   tools/build-task1-chart-manifest.mjs). Two forms arrive:

   - an address, on the open site: "/ielts-website/pics/writing/imported/
     wt-132-task1.webp". The Worker fetches it only when it names a file in
     that list, from the configured site (SITE_URL), or from a localhost
     origin that ALLOWED_ORIGINS already allows when the request comes from
     that origin (local development). The address is rebuilt from the file
     name, so nothing the browser wrote beyond the file name is ever fetched.
   - a data address ("data:image/png;base64,..."), in a commercial build,
     which does not publish the charts (astro.config.mjs, TRIAL_UNPUBLISHED)
     and carries them inline. Nothing is fetched; the bytes are hashed.

   Anything else is ignored: another site, another folder, an unknown file, a
   changed file, an oversized one. At most two images are attached (one Task 1
   question, a before-and-after map, has two). When none qualifies, grading
   runs exactly as it did before this module existed, on the text alone. */

import { TASK1_CHARTS } from './task1-charts';

export const MAX_VISUALS = 2;
/** The largest chart in the folder is about 140 KB. */
export const MAX_VISUAL_BYTES = 512 * 1024;
const FETCH_TIMEOUT_MS = 8000;
const DEFAULT_SITE_URL = 'https://lxson777-tech.github.io/ielts-website/';
const CHART_DIR = '/pics/writing/imported/';

export interface Task1Visual {
  /** The chart's file name in public/pics/writing/imported. */
  file: string;
  mimeType: string;
  base64: string;
}

export interface VisualEnv {
  SITE_URL?: string;
  ALLOWED_ORIGINS: string;
}

const MIME_BY_EXT: Record<string, string> = {
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  webp: 'image/webp',
  gif: 'image/gif',
};

function mimeOf(file: string): string | null {
  return MIME_BY_EXT[file.slice(file.lastIndexOf('.') + 1).toLowerCase()] ?? null;
}

/** Every <img> src in the question, in order, raw. */
export function imageSources(promptHtml: string): string[] {
  const out: string[] = [];
  for (const m of promptHtml.matchAll(/<img\b[^>]*?\bsrc\s*=\s*(?:"([^"]*)"|'([^']*)')/gi)) {
    const src = (m[1] ?? m[2] ?? '').trim();
    if (src) out.push(src);
  }
  return out;
}

/** The question with inline data addresses removed, for the length check:
    the text of a question is short, its inline chart is not. */
export function withoutInlineImages(promptHtml: string): string {
  return promptHtml.replace(/data:image\/[a-z0-9.+-]+;base64,[A-Za-z0-9+/=\s]*/gi, '');
}

async function sha256Hex(bytes: Uint8Array<ArrayBuffer>): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

/** The chart file these bytes are, or null when they are not one of ours. */
async function knownChart(bytes: Uint8Array<ArrayBuffer>): Promise<string | null> {
  if (bytes.byteLength === 0 || bytes.byteLength > MAX_VISUAL_BYTES) return null;
  const hash = await sha256Hex(bytes);
  for (const [file, known] of Object.entries(TASK1_CHARTS)) if (known === hash) return file;
  return null;
}

function toBase64(bytes: Uint8Array): string {
  let bin = '';
  for (let i = 0; i < bytes.length; i += 0x8000) bin += String.fromCharCode(...bytes.subarray(i, i + 0x8000));
  return btoa(bin);
}

function fromBase64(b64: string): Uint8Array<ArrayBuffer> | null {
  try {
    const bin = atob(b64.replace(/\s+/g, ''));
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
  } catch {
    return null;
  }
}

function isLocalhost(origin: string): boolean {
  try {
    const host = new URL(origin).hostname;
    return host === 'localhost' || host === '127.0.0.1' || host === '[::1]';
  } catch {
    return false;
  }
}

/** The site the charts are published on, and its base path ("/ielts-website"). */
function siteOf(env: VisualEnv): { origin: string; base: string } {
  let url: URL;
  try {
    url = new URL(env.SITE_URL || DEFAULT_SITE_URL);
  } catch {
    url = new URL(DEFAULT_SITE_URL);
  }
  return { origin: url.origin, base: url.pathname.replace(/\/+$/, '') };
}

/** Where a chart address may be fetched from: the site itself, and, for
    local development, a localhost origin ALLOWED_ORIGINS lists, only when
    the request itself comes from it. Returns the canonical address to fetch
    and the chart file, or null. */
export function chartAddress(src: string, env: VisualEnv, requestOrigin: string | null): { url: string; file: string } | null {
  const site = siteOf(env);
  const allowed = env.ALLOWED_ORIGINS.split(',').map((o) => o.trim()).filter(Boolean);
  const devOrigin = requestOrigin && isLocalhost(requestOrigin) && allowed.includes(requestOrigin) ? requestOrigin : null;
  let url: URL;
  try {
    url = new URL(src, `${devOrigin ?? site.origin}${site.base}/`);
  } catch {
    return null;
  }
  if (url.protocol !== 'https:' && url.protocol !== 'http:') return null;
  if (url.origin !== site.origin && url.origin !== devOrigin) return null;
  if (url.search || url.hash || url.username || url.password) return null;
  // "/ielts-website/pics/writing/imported/<file>", or the same without the
  // base (plain Node has no BASE_URL, so withBase() leaves it off there).
  const path = url.pathname;
  const rest = path.startsWith(`${site.base}${CHART_DIR}`)
    ? path.slice(site.base.length + CHART_DIR.length)
    : path.startsWith(CHART_DIR)
      ? path.slice(CHART_DIR.length)
      : null;
  if (rest === null || !/^[A-Za-z0-9._-]+$/.test(rest) || !Object.hasOwn(TASK1_CHARTS, rest)) return null;
  return { url: `${url.origin}${site.base}${CHART_DIR}${rest}`, file: rest };
}

async function fetchChart(fetchFn: typeof fetch, address: { url: string; file: string }): Promise<Task1Visual | null> {
  let resp: Response;
  try {
    resp = await fetchFn(address.url, { method: 'GET', redirect: 'manual', signal: AbortSignal.timeout(FETCH_TIMEOUT_MS) });
  } catch {
    return null;
  }
  if (resp.status !== 200) return null;
  const declared = Number(resp.headers.get('Content-Length') ?? '0');
  if (declared > MAX_VISUAL_BYTES) return null;
  let bytes: Uint8Array<ArrayBuffer>;
  try {
    bytes = new Uint8Array(await resp.arrayBuffer());
  } catch {
    return null;
  }
  const file = await knownChart(bytes);
  // The bytes must be the very file the address named.
  if (file !== address.file) return null;
  const mimeType = mimeOf(file);
  return mimeType ? { file, mimeType, base64: toBase64(bytes) } : null;
}

async function inlineChart(src: string): Promise<Task1Visual | null> {
  const m = src.match(/^data:image\/(png|jpeg|webp|gif);base64,([A-Za-z0-9+/=\s]+)$/i);
  if (!m) return null;
  // Base64 is four characters for every three bytes.
  if (m[2]!.length > Math.ceil((MAX_VISUAL_BYTES * 4) / 3) + 16) return null;
  const bytes = fromBase64(m[2]!);
  if (!bytes) return null;
  const file = await knownChart(bytes);
  const mimeType = file ? mimeOf(file) : null;
  return file && mimeType ? { file, mimeType, base64: toBase64(bytes) } : null;
}

/** The Task 1 charts to attach for this question: site charts only, at most
    MAX_VISUALS, in the order the question shows them, no file twice. Never
    throws; an image that cannot be confirmed is simply left out. */
export async function task1Visuals(
  fetchFn: typeof fetch,
  env: VisualEnv,
  promptHtml: string,
  requestOrigin: string | null,
): Promise<Task1Visual[]> {
  const out: Task1Visual[] = [];
  const seen = new Set<string>();
  for (const src of imageSources(promptHtml)) {
    if (out.length >= MAX_VISUALS) break;
    let visual: Task1Visual | null = null;
    try {
      if (/^data:/i.test(src)) visual = await inlineChart(src);
      else {
        const address = chartAddress(src, env, requestOrigin);
        if (address && !seen.has(address.file)) visual = await fetchChart(fetchFn, address);
      }
    } catch {
      visual = null;
    }
    if (visual && !seen.has(visual.file)) {
      seen.add(visual.file);
      out.push(visual);
    }
  }
  return out;
}
