/* Generated by tools/build-task1-chart-manifest.mjs from
   public/pics/writing/imported. Do not edit by hand: re-run the tool.

   The essay grader attaches a Task 1 chart to the model only when its bytes
   hash to one of these values (see ./task1-visual.ts). */

export const TASK1_CHARTS: Readonly<Record<string, string>> = {
  'wt-103-task1.png': 'de2333f22b4aa92d7e85b9f5cc8e757ee964694c221340e5a060a42a408535d4',
  'wt-104-task1.png': 'e8a043f75911ecf8f19acdf9fd6a49e9b778c910b86556fe468912b3db3cef7c',
  'wt-105-task1.png': '8ae555a82438e84785d9346ad203cfee1d9c1f10a0280ab82a66b301dbaba026',
  'wt-106-task1.png': '943b64aa8ec36895ba168ffb8871ed31280df3cb45c0006f90301048b75e2c1a',
  'wt-107-task1.png': '548852cd8c09d68197eec57bc51dfd20c074d1970d9f85ea788b4836c03000ae',
  'wt-108-task1.png': 'a78cfad32cc9c0c4760ed33a660e31963e2371de1761f246c50faa770b407b59',
  'wt-109-task1.png': 'fa7e9447db933036e5b7618dbdc7d40813aa081db24532808dd4479a47a4b4ea',
  'wt-110-task1.png': '2b93dcdf6f03ec0434007806482164c88a3502d59eb8f333e5a7963bed0d8898',
  'wt-111-task1.png': '737bc53f95eb6f13de4e490db832badb7a394287f124a430b6b06e8f4cb9b5ad',
  'wt-112-task1.png': 'b8cf95e2849262b330d20c582b5acf9c6e08a4017880ae9b7cde4ced1c097774',
  'wt-113-task1.png': 'ab359ce49cc1be624641bb17fd7d2667496358e0297466a0933f3aa27c20e9ec',
  'wt-114-task1.png': '38a182e8b24cbcfb14fe7de7a1063edd8e997924c2f8999412fcafaf06d0e0c5',
  'wt-115-task1.png': 'd6bbc80aed0ea820753fc60fad0c5a4c6b30a1bbf6013c230ab5aae0ae971b99',
  'wt-116-task1.png': '4f8547e423ccdcb241a3cedc5d54394d0a1d978ce5d4436f936c697779f25b18',
  'wt-117-task1.jpg': '9e0433a0e0143cd9e8a386a7ca75ecaf042bc2e0efd234c7e5357b6f31cbb139',
  'wt-118-task1.jpg': 'f7f8f1bdf4d211fb4d3ac3086a9e08723e680fde65d6c17984497f6ce4ec9c75',
  'wt-119-task1.jpg': 'ce0c56ae9225f69a76226f5eef6154f96c21e29627bad378e181ab68ecdece50',
  'wt-120-task1.jpg': '03ac324222d935c584136f50afe06fe0735996ff5579f0d17f9aa8f7d52f1afb',
  'wt-121-task1.png': 'a1d3e461af87a70a38a20482df995b37caf91f951d5a607c9f7613e66ca1cd08',
  'wt-122-task1.png': '7b25b7441e780a8d09a469c3589ee8dd949d66d20d74cab72696e342514e7817',
  'wt-123-task1.png': '5f63068758f189890e36da0da3565ce4e4aeec78f5f211b46d93ab4f62d3deff',
  'wt-124-task1.png': '7f5493e02c83c3187e034b2452a47d22be01c3f3fbdcf40cc32e247c0032bd1c',
  'wt-125-task1.webp': '2755b050a5fe01a3400ee1058581301acc5f6e682ea810e8d92d1936584783f3',
  'wt-126-task1-2.webp': 'c1cebf7aeeaea9e6d07e404f3dfb9832339be48dac0da31a7fed6216a988e879',
  'wt-126-task1.webp': '7b4442f05bb30e5faf8d7e993cb1464bfdd48c0870eeffccc848b061e29ed99f',
  'wt-127-task1.webp': 'd928398f6f2a8a9a8d70c7f4a48472f1117f1d88447824a63bebfc30d17939ec',
  'wt-128-task1.webp': '247c71fab2c2eb9cb50dd91c8c7b136a17fd0f4c1e6b44f13fca29e3a9576484',
  'wt-129-task1.webp': '21a373298f54f8a84385170ffbd2556e86591ef79823d45fe8de13a08ff09cc2',
  'wt-130-task1.webp': '764cc2c0428de02d0113f5d4c1b55b5d1405f6b70d34431b3ad9c7639b61670a',
  'wt-131-task1.webp': '2ef45b941aec87754d62cf712c0cacd951485dcff4299867fdfae306da355d8f',
  'wt-132-task1.webp': 'd472f1e4cb4bcb5fe932b553a4bc2450f2d3e41c7ec3c8df334288ff2cca2f7a',
};
