/* Per-question writing plans: unlike src/data/writing-structures.ts (one
   generic structure guide per essay TYPE, e.g. "Opinion Essay"), a
   WritingPlan is specific to a single PROMPT — its own key points, its own
   position, its own paragraph tips, drawn from what this particular
   question actually asks. Generated by tools/generate_writing_plans.py (see
   workflows/generate_writing_plans.md), stored in src/data/writing-plans.ts,
   rendered by the "This question" tab in WritingCoachPanel.tsx. */

export type WritingPlanTask = 'task1' | 'task2';

export interface WritingPlanParagraph {
  /** "Introduction", "Body 1", "Overview", ... */
  label: string;
  /** one sentence: what this paragraph needs to accomplish */
  goal: string;
  /** 2 to 3 specific tips for THIS question, not generic advice */
  tips: string[];
  /** a sentence starter the student may adapt, not copy verbatim */
  starter: string;
}

export interface WritingPlanVocabEntry {
  phrase: string;
  /** ~5 words on when/how to use it */
  use: string;
}

export interface WritingPlan {
  promptId: string;
  task: WritingPlanTask;
  /** plain-words question type, e.g. "Opinion (agree or disagree)", "Line graph over time", "Process diagram" */
  questionType: string;
  /** 1 to 2 sentences: what exactly this question wants, including any trap
      (two parts, "to what extent", both views AND your opinion, compare or describe) */
  whatItAsks: string;
  /** Task 2: 3 to 4 concrete ideas/arguments for THIS topic, each with a hint of an example.
      Task 1: the 3 to 5 key features to report (biggest, smallest, trend, exception, comparison),
      in plain words, based on the actual chart/diagram. */
  keyPoints: string[];
  /** Task 2 only: a clear suggested position, or how to pick one */
  position?: string;
  /** Task 1 only: 3 to 4 guiding questions or prompts that lead the student to
      build their own overview. Never a finished sentence, never the answer. */
  overviewHints?: string[];
  /** 4 to 5 paragraphs */
  paragraphs: WritingPlanParagraph[];
  /** 6 to 8 topic-specific words/collocations */
  vocabulary: WritingPlanVocabEntry[];
  /** 3 specific mistakes students make on THIS question */
  pitfalls: string[];
  /** one line: minutes for planning, writing, checking */
  timing: string;
}
