import sys; sys.path.insert(0, ".")
from playwright.sync_api import sync_playwright
from c_common import GATED, account, new_ctx, ready
OPEN="http://localhost:4442/ielts-website"; OUT=sys.argv[1]; res=[]
def check(n, ok, d=""): res.append(ok); print("PASS" if ok else "FAIL", n, d)
with sync_playwright() as p:
    b=p.chromium.launch()
    for w,h,tag in [(1440,900,"desk"),(390,844,"phone"),(320,700,"small")]:
        pg=b.new_page(viewport={"width":w,"height":h}, locale="en-US", is_mobile=(tag!="desk"), has_touch=(tag!="desk")); errs=[]; pg.on("pageerror", lambda e: errs.append(str(e)[:120]))
        pg.goto(OPEN+"/tests", wait_until="networkidle"); pg.wait_for_timeout(1200)
        H=pg.evaluate("document.documentElement.scrollHeight")
        check(f"{tag}: Tests page has no paper list", pg.locator("[data-discovery-item]").count()==0, f"height {H}")
        link=pg.get_by_role("link", name="See all papers")
        check(f"{tag}: 'See all papers' link present", link.count()==1)
        if tag=="desk": pg.screenshot(path=f"{OUT}/tests-desk.png", full_page=True)
        link.click(); pg.wait_for_url("**/tests/all"); pg.wait_for_timeout(1500)
        items=pg.locator("[data-discovery-item]:visible").count()
        check(f"{tag}: all-papers page lists papers", items==12, items)
        check(f"{tag}: Tests tab still lit in the menu", pg.locator(".ws-tab.is-active, .ws-tabbar-link.is-active", has_text="Tests").count()>=1)
        pg.get_by_role("tab", name="Listening").click(); pg.wait_for_timeout(400)
        first=pg.locator("[data-discovery-item]:visible a").first.get_attribute("href")
        check(f"{tag}: Listening tab shows listening papers", "listening" in first, first)
        badges=pg.locator("[data-checkpoint-badge]").count()
        check(f"{tag}: Unseen badges still shown", badges>0, badges)
        pg.get_by_role("button", name="Show more").click(); pg.wait_for_timeout(300)
        check(f"{tag}: Show more adds papers", pg.locator("[data-discovery-item]:visible").count()>12)
        check(f"{tag}: no sideways scroll", pg.evaluate("document.documentElement.scrollWidth <= innerWidth"))
        if tag=="desk": pg.screenshot(path=f"{OUT}/all-desk.png", full_page=True)
        pg.get_by_role("link", name="Back to Tests").click(); pg.wait_for_url("**/tests"); 
        check(f"{tag}: Back to Tests works", pg.url.endswith("/tests"))
        check(f"{tag}: no page errors", not errs, errs); pg.close()
    ctx=new_ctx(b,"en",1440,900); pg=ctx.new_page(); errs=[]; pg.on("pageerror", lambda e: errs.append(str(e)[:120]))
    account(pg,"free","allpapers")
    pg.goto(GATED+"/tests/all", wait_until="domcontentloaded"); ready(pg,2500)
    check("gated free: page renders the list", pg.locator("[data-discovery-item]").count()>0)
    pg.locator("[data-discovery-item]:visible a").first.click(); pg.wait_for_timeout(1500)
    dlg=pg.locator("[role=dialog]:visible").count()
    check("gated free: a paper link asks to upgrade instead of opening", dlg>0 or "/tests/all" in pg.url, pg.url)
    check("gated free: no page errors", not errs, errs)
    b.close()
print(sum(res),"/",len(res))
