"""Generate per-question writing plans for the Writing Trainer's coach.

Unlike src/data/writing-structures.ts (one generic structure guide per essay
TYPE, e.g. "Opinion Essay"), a WritingPlan (src/lib/writing/plans.ts) is
specific to a single PROMPT: its own key points, its own suggested position,
paragraph-by-paragraph tips that name the actual topic, drawn from what that
one question asks. This script calls the OpenAI Responses API once per
prompt (Task 1 prompts include the chart/diagram image, so the plan reflects
what is actually drawn) and merges the results into src/data/writing-plans.ts.

Prompts are read from src/data/writing-prompts-imported.ts by parsing the
generated TypeScript structurally (parse_prompts() below) rather than
hand-copying data -- there is no JSON source for them, and the file is
machine-generated by tools/import_writing.py with a fixed template, so a
small structural parser is reliable here.

Usage (run from the project root):

    python tools/generate_writing_plans.py                                  # all prompts
    python tools/generate_writing_plans.py --ids pte-wt-132-task1 pte-wt-132-task2
    python tools/generate_writing_plans.py --limit 10                       # first 10 prompts with no plan yet

Cost: roughly a few cents per prompt (see workflows/generate_writing_plans.md).
Reads OPENAI_API_KEY from the environment / .env, falling back to the main
checkout's workers/grade-essay/.dev.vars. The key is never printed and is
redacted from any error output.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import re
import sys
import time
from datetime import date
from pathlib import Path

import requests

sys.path.insert(0, str(Path(__file__).parent))
from utils import ROOT, tmp_path  # noqa: E402

PROMPTS_FILE = ROOT / "src" / "data" / "writing-prompts-imported.ts"
OUT_FILE = ROOT / "src" / "data" / "writing-plans.ts"
CACHE_FILE = tmp_path("writing-plans-cache.json")
FALLBACK_DEV_VARS = Path(r"C:\Users\Alex\Desktop\IELTS website\workers\grade-essay\.dev.vars")

MODEL = os.getenv("WRITING_PLAN_MODEL", "gpt-5.6-sol")
REASONING_EFFORT = "medium"
INPUT_COST_PER_MILLION = 4.0
OUTPUT_COST_PER_MILLION = 20.0

VARIANT_LABELS = {
    "opinion": "Opinion (agree or disagree)",
    "discussion": "Discussion (discuss both views)",
    "problem-solution": "Problem / solution (or cause / effect)",
    "advantages-disadvantages": "Advantages and disadvantages",
    "two-part": "Two-part question",
    "line-graph": "Line graph over time",
    "bar-chart": "Bar chart",
    "pie-chart": "Pie chart",
    "table": "Table",
    "combination": "Combination of visuals (chart and/or table)",
    "process": "Process diagram",
    "map": "Map or plan (before/after)",
}


# ── reading the prompt pool ────────────────────────────────────────────────

_OBJ_RE = re.compile(r"\n  \{\n(.*?)\n  \},", re.S)
_QSTR_RE = re.compile(r'"(?:[^"\\]|\\.)*"')


def parse_prompts() -> list[dict]:
    """Structurally parses src/data/writing-prompts-imported.ts (generated by
    tools/import_writing.py, never hand-edited -- see its header comment) into
    plain dicts. Reads id/task/variant/title/minWords plus the prompt's plain
    text and, for Task 1, the local image path(s) under public/."""
    text = PROMPTS_FILE.read_text(encoding="utf-8")
    array_start = text.index("IMPORTED_WRITING_PROMPTS: EssayPrompt[] = [")
    array_text = text[array_start:]

    prompts = []
    for m in _OBJ_RE.finditer(array_text):
        block = m.group(1)
        prompts.append(_parse_prompt_block(block))
    return prompts


def _parse_prompt_block(block: str) -> dict:
    def field(name: str) -> str | None:
        m = re.search(rf"{name}: '([^']+)',", block)
        return m.group(1) if m else None

    id_ = field("id")
    task = field("task")
    variant = field("variant")

    title_m = re.search(rf"title: ({_QSTR_RE.pattern}),", block)
    title = json.loads(title_m.group(1)) if title_m else ""

    minwords_m = re.search(r"minWords: (\d+),", block)
    min_words = int(minwords_m.group(1)) if minwords_m else 0

    if "promptHtml: `" in block:
        ph_m = re.search(r"promptHtml: `(.*?)`,\n", block, re.S)
        raw = ph_m.group(1) if ph_m else ""
        raw = raw.replace("\\`", "`").replace("\\${", "${").replace("\\\\", "\\")
        images = re.findall(r"src=\"\$\{withBase\('([^']+)'\)\}\"", raw)
        text_only = re.sub(r"<img[^>]*>", "", raw).strip()
    else:
        ph_m = re.search(rf"promptHtml: ({_QSTR_RE.pattern}),", block)
        text_only = json.loads(ph_m.group(1)) if ph_m else ""
        images = []

    return {
        "id": id_,
        "task": task,
        "variant": variant,
        "title": title,
        "minWords": min_words,
        "promptText": re.sub(r"<[^>]+>", " ", text_only).strip(),
        "images": images,
    }


# ── API key ─────────────────────────────────────────────────────────────

def resolve_api_key() -> str:
    key = os.getenv("OPENAI_API_KEY")
    if key:
        return key
    if FALLBACK_DEV_VARS.exists():
        for line in FALLBACK_DEV_VARS.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith("OPENAI_API_KEY="):
                value = line.split("=", 1)[1].strip().strip('"').strip("'")
                if value:
                    return value
    print("Missing OPENAI_API_KEY: not in the environment or .env, and not found in")
    print(f"  {FALLBACK_DEV_VARS}")
    print("Add it to one of those and try again.")
    sys.exit(1)


def redact(text: str, key: str) -> str:
    return text.replace(key, "[REDACTED]") if key else text


# ── dash stripping (site copy standard has no em/en dashes) ──────────────

_DASH_NUM_RE = re.compile(r"(\d)[\u2013\u2014](\d)")
_DASH_GENERAL_RE = re.compile(r"\s*[\u2014\u2013]\s*")


def strip_dashes(value):
    if isinstance(value, str):
        value = _DASH_NUM_RE.sub(r"\1-\2", value)
        value = _DASH_GENERAL_RE.sub(", ", value)
        value = re.sub(r",\s*,", ",", value)
        return value
    if isinstance(value, list):
        return [strip_dashes(v) for v in value]
    if isinstance(value, dict):
        return {k: strip_dashes(v) for k, v in value.items()}
    return value


# ── the model call ────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are an experienced IELTS Writing teacher. For the single question you are \
given, produce a specific, concrete plan that a band 6 student could follow to reach band 7 on \
THIS question.

Rules:
- Be concrete: name the actual topic, the actual ideas, and for Task 1 the actual numbers, \
labels or features you can see. Never write advice that would fit any other question of the \
same type -- if a sentence could be pasted into a different prompt's plan unchanged, rewrite it.
- Task 1 (a chart, graph, table, process or map): you are given the image. Read it before \
writing keyPoints, position them as the 3 to 5 features an examiner expects reported (the \
biggest or smallest, the overall trend, any exception, a comparison between groups). Do NOT \
write a finished overview sentence anywhere. Instead write "overviewHints": 3 to 4 short \
guiding questions or instructions that point the student at what to look for (which line ends \
highest, is there a crossing point, which category is the exception, and so on) WITHOUT stating \
the answer. A student who reads only the hints must still look at the chart to write the \
overview. Never name a specific value, direction, category or ranking in a hint, and never \
paraphrase the pattern you can see. Vary the hints by visual type (trend chart, static \
comparison, two visuals, process, map) and include one hint about technique, such as starting \
with "Overall," and keeping it to one or two sentences with no numbers.
- Task 2 (an essay): keyPoints are 3 to 4 concrete arguments or ideas for THIS topic, each with \
a hint of a real-world example a student could develop. Give a clear suggested position (or, if \
genuinely balanced, say exactly how to pick one and commit). Set "overviewHints" to an empty \
array, since Task 2 essays have no overview paragraph.
- paragraphs: 4 to 5 rows. Task 1 is always Introduction, Overview, Detail 1, Detail 2. Task 2 \
is Introduction, Body 1, Body 2, optionally Body 3, Conclusion -- pick the shape that matches \
this question (for example a two-part question gets one body paragraph per part; an opinion \
question may want a concession paragraph). Each paragraph needs a one-sentence goal, 2 to 3 \
tips specific to this question (not "use topic sentences"), and one sentence starter the \
student can adapt, not copy word for word. For the Task 1 "Overview" paragraph specifically: \
the goal and tips must guide the student to notice the pattern themselves (for example "decide \
which line ends highest" or "work out whether every category moves the same way") rather than \
stating what the pattern is, and the starter must be only a neutral sentence stem such as \
"Overall, it is clear that" or "Overall, the most noticeable feature is" with no chart-specific \
content after it. Never let the Overview paragraph's goal, tips or starter give away the answer \
that the hints are meant to withhold.
- vocabulary: 6 to 8 words or collocations for THIS topic specifically, each with a five-word \
note on when to use it.
- pitfalls: exactly 3 mistakes students actually make on THIS question, not generic IELTS advice.
- timing: one line, minutes for planning, writing and checking, appropriate to the task \
(roughly 5/30/5 for Task 2, 5/13/2 for Task 1).
- British spelling throughout.
- Never use an em dash or en dash (\u2014 or \u2013) anywhere in the output. Use a comma, a \
period, parentheses, or "and"/"but" instead.
- Set "position" to an empty string for Task 1 (the field Task 1 doesn't use).
- Never be generic. Every field must be traceable to this specific question."""


def build_user_text(prompt: dict) -> str:
    variant_label = VARIANT_LABELS.get(prompt["variant"], prompt["variant"])
    lines = [
        f"TASK: {prompt['task']} ({'IELTS Writing Task 2 essay' if prompt['task'] == 'task2' else 'IELTS Writing Task 1 Academic report'})",
        f"QUESTION TYPE: {variant_label}",
        f"TITLE: {prompt['title']}",
        f"MINIMUM WORDS: {prompt['minWords']}",
        f"QUESTION TEXT: {prompt['promptText']}",
    ]
    if prompt["images"]:
        lines.append("The chart/diagram for this question is attached as an image. Read it carefully before writing keyPoints and the overview hints.")
    return "\n".join(lines)


RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "questionType": {"type": "string"},
        "whatItAsks": {"type": "string"},
        "keyPoints": {"type": "array", "items": {"type": "string"}},
        "position": {"type": ["string", "null"]},
        "overviewHints": {"type": "array", "items": {"type": "string"}},
        "paragraphs": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "label": {"type": "string"},
                    "goal": {"type": "string"},
                    "tips": {"type": "array", "items": {"type": "string"}},
                    "starter": {"type": "string"},
                },
                "required": ["label", "goal", "tips", "starter"],
                "additionalProperties": False,
            },
        },
        "vocabulary": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "phrase": {"type": "string"},
                    "use": {"type": "string"},
                },
                "required": ["phrase", "use"],
                "additionalProperties": False,
            },
        },
        "pitfalls": {"type": "array", "items": {"type": "string"}},
        "timing": {"type": "string"},
    },
    "required": [
        "questionType", "whatItAsks", "keyPoints", "position", "overviewHints",
        "paragraphs", "vocabulary", "pitfalls", "timing",
    ],
    "additionalProperties": False,
}


def image_data_url(local_web_path: str) -> str:
    file_path = ROOT / "public" / local_web_path.lstrip("/")
    data = file_path.read_bytes()
    ext = file_path.suffix.lower().lstrip(".")
    mime = {"webp": "image/webp", "png": "image/png", "jpg": "image/jpeg", "jpeg": "image/jpeg"}.get(ext, "image/png")
    b64 = base64.b64encode(data).decode("ascii")
    return f"data:{mime};base64,{b64}"


def call_openai(api_key: str, prompt: dict) -> dict:
    content = [{"type": "input_text", "text": build_user_text(prompt)}]
    for image_path in prompt["images"]:
        content.append({"type": "input_image", "image_url": image_data_url(image_path)})

    body = {
        "model": MODEL,
        "instructions": SYSTEM_PROMPT,
        "input": [{"role": "user", "content": content}],
        "reasoning": {"effort": REASONING_EFFORT},
        "text": {
            "format": {
                "type": "json_schema",
                "name": "writing_plan",
                "strict": True,
                "schema": RESPONSE_SCHEMA,
            }
        },
        "store": False,
    }
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}

    backoff = [5, 15, 60]
    last_error = None
    for attempt, wait in enumerate([0] + backoff):
        if wait:
            time.sleep(wait)
        try:
            response = requests.post(
                "https://api.openai.com/v1/responses", headers=headers, json=body, timeout=180
            )
        except requests.RequestException as exc:
            last_error = redact(str(exc), api_key)
            continue
        if response.status_code == 429 or response.status_code >= 500:
            last_error = redact(f"HTTP {response.status_code}: {response.text[:300]}", api_key)
            continue
        if response.status_code != 200:
            raise RuntimeError(redact(f"HTTP {response.status_code}: {response.text[:500]}", api_key))
        return response.json()
    raise RuntimeError(f"Gave up after retries: {last_error}")


def parse_output(response_json: dict) -> tuple[dict, dict]:
    """Returns (plan_fields, usage). Raises if the shape doesn't match."""
    if response_json.get("status") == "incomplete" or response_json.get("error"):
        raise RuntimeError(f"Model returned an error/incomplete status: {response_json.get('error') or response_json.get('status')}")
    for item in response_json.get("output", []):
        if item.get("type") != "message":
            continue
        for c in item.get("content", []):
            if c.get("type") == "output_text":
                parsed = json.loads(c["text"])
                usage = response_json.get("usage", {})
                return parsed, usage
    raise RuntimeError("No output_text found in the response.")


# ── merging + rendering src/data/writing-plans.ts ────────────────────────

def load_cache() -> dict:
    if CACHE_FILE.exists():
        return json.loads(CACHE_FILE.read_text(encoding="utf-8"))
    return {}


def save_cache(cache: dict) -> None:
    CACHE_FILE.write_text(json.dumps(cache, ensure_ascii=False, indent=2), encoding="utf-8")


def dq(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_string_array(values: list[str], indent: str) -> str:
    if not values:
        return "[]"
    items = ",\n".join(f"{indent}  {dq(v)}" for v in values)
    return f"[\n{items},\n{indent}]"


def render_paragraph(p: dict, indent: str) -> str:
    tips = ", ".join(dq(t) for t in p["tips"])
    return (
        f"{indent}{{ label: {dq(p['label'])}, goal: {dq(p['goal'])}, "
        f"tips: [{tips}], starter: {dq(p['starter'])} }}"
    )


def render_vocab(v: dict, indent: str) -> str:
    return f"{indent}{{ phrase: {dq(v['phrase'])}, use: {dq(v['use'])} }}"


def render_plan(plan: dict) -> str:
    lines = [
        f"  {dq(plan['promptId'])}: {{",
        f"    promptId: {dq(plan['promptId'])},",
        f"    task: {dq(plan['task'])},",
        f"    questionType: {dq(plan['questionType'])},",
        f"    whatItAsks: {dq(plan['whatItAsks'])},",
        f"    keyPoints: {render_string_array(plan['keyPoints'], '    ')},",
    ]
    if plan["task"] == "task2" and plan.get("position"):
        lines.append(f"    position: {dq(plan['position'])},")
    if plan["task"] == "task1" and plan.get("overviewHints"):
        lines.append(f"    overviewHints: {render_string_array(plan['overviewHints'], '    ')},")
    paragraphs = ",\n".join(render_paragraph(p, "      ") for p in plan["paragraphs"])
    lines.append(f"    paragraphs: [\n{paragraphs},\n    ],")
    vocab = ",\n".join(render_vocab(v, "      ") for v in plan["vocabulary"])
    lines.append(f"    vocabulary: [\n{vocab},\n    ],")
    lines.append(f"    pitfalls: {render_string_array(plan['pitfalls'], '    ')},")
    lines.append(f"    timing: {dq(plan['timing'])},")
    lines.append("  },")
    return "\n".join(lines)


HEADER_TEMPLATE = """/* Per-question writing plans -- generated by tools/generate_writing_plans.py
   on {date}. Do not hand-edit; re-run the tool (see
   workflows/generate_writing_plans.md) and it will regenerate the prompts you
   ask for while leaving every other entry untouched. */

import type {{ WritingPlan }} from '../lib/writing/plans';

export const WRITING_PLANS: Record<string, WritingPlan> = {{
"""

FOOTER = """};

export function getWritingPlan(promptId: string): WritingPlan | undefined {
  return WRITING_PLANS[promptId];
}
"""


def write_output(cache: dict, ordered_ids: list[str]) -> None:
    ordered = [pid for pid in ordered_ids if pid in cache]
    leftover = [pid for pid in cache if pid not in ordered_ids]
    ordered += sorted(leftover)

    body = "\n".join(render_plan(cache[pid]) for pid in ordered)
    header = HEADER_TEMPLATE.format(date=date.today().isoformat())
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(header + body + "\n" + FOOTER, encoding="utf-8")


# ── main ───────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Generate per-question IELTS writing plans.")
    parser.add_argument("--ids", nargs="+", help="Specific prompt ids to (re)generate.")
    parser.add_argument("--limit", type=int, help="Generate plans for the first N prompts that don't have one yet.")
    args = parser.parse_args()

    prompts = parse_prompts()
    prompts_by_id = {p["id"]: p for p in prompts}
    ordered_ids = [p["id"] for p in prompts]

    cache = load_cache()

    if args.ids:
        unknown = [i for i in args.ids if i not in prompts_by_id]
        if unknown:
            print(f"Unknown prompt id(s), not found in {PROMPTS_FILE.name}: {', '.join(unknown)}")
            sys.exit(1)
        targets = args.ids
    elif args.limit:
        missing = [pid for pid in ordered_ids if pid not in cache]
        targets = missing[: args.limit]
        if not targets:
            print("Every prompt already has a plan. Pass --ids to regenerate specific ones.")
            return
    else:
        targets = ordered_ids

    print(f"Generating {len(targets)} plan(s) with model {MODEL} (reasoning effort: {REASONING_EFFORT})...")
    api_key = resolve_api_key()

    total_input_tokens = 0
    total_output_tokens = 0
    failures: list[tuple[str, str]] = []

    for pid in targets:
        prompt = prompts_by_id[pid]
        try:
            response_json = call_openai(api_key, prompt)
            fields, usage = parse_output(response_json)
        except Exception as exc:  # noqa: BLE001 - report and continue with the rest
            failures.append((pid, redact(str(exc), api_key)))
            print(f"  {pid}: FAILED -- {redact(str(exc), api_key)}")
            continue

        fields = strip_dashes(fields)
        plan = {
            "promptId": pid,
            "task": prompt["task"],
            **fields,
        }
        cache[pid] = plan

        in_tok = usage.get("input_tokens", 0)
        out_tok = usage.get("output_tokens", 0)
        total_input_tokens += in_tok
        total_output_tokens += out_tok
        cost = (in_tok * INPUT_COST_PER_MILLION + out_tok * OUTPUT_COST_PER_MILLION) / 1_000_000
        print(f"  {pid}: {in_tok} in / {out_tok} out tokens, ${cost:.4f}")

    save_cache(cache)
    write_output(cache, ordered_ids)

    total_cost = (total_input_tokens * INPUT_COST_PER_MILLION + total_output_tokens * OUTPUT_COST_PER_MILLION) / 1_000_000
    print(f"\nWrote {OUT_FILE} with {len(cache)} plan(s) total.")
    print(f"This run: {total_input_tokens} input tokens, {total_output_tokens} output tokens, ${total_cost:.4f} estimated.")
    if failures:
        print(f"{len(failures)} prompt(s) failed and were skipped:")
        for pid, reason in failures:
            print(f"  - {pid}: {reason}")


if __name__ == "__main__":
    main()
